In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
import numpy as np
your_array = np.array([1, 2, 3, 4, 5])
result = np.all(your_array != 0)
if result:
    print("None of the elements in the array are zero.")
else:
    print("There are zero elements in the array.")

None of the elements in the array are zero.


In [3]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 2, 2, 5, 4])
greater_than_result = array1 > array2
greater_equal_result = array1 >= array2
less_than_result = array1 < array2
less_equal_result = array1 <= array2
print("Array1 > Array2:")
print(greater_than_result)

print("\nArray1 >= Array2:")
print(greater_equal_result)

print("\nArray1 < Array2:")
print(less_than_result)

print("\nArray1 <= Array2:")
print(less_equal_result)

Array1 > Array2:
[False False  True False  True]

Array1 >= Array2:
[False  True  True False  True]

Array1 < Array2:
[ True False False  True False]

Array1 <= Array2:
[ True  True False  True False]


In [4]:
import numpy as np
my_array = np.array([1, 7, 13, 105])
memory_size_bytes = my_array.nbytes
memory_size_kb = memory_size_bytes / 1024
print(f"Array: {my_array}")
print(f"Size of memory occupied by the array: {memory_size_bytes} bytes ({memory_size_kb:.2f} KB)")

Array: [  1   7  13 105]
Size of memory occupied by the array: 16 bytes (0.02 KB)


In [5]:
import numpy as np
my_array = np.arange(30, 71)
print(my_array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [6]:
import numpy as np
even_integers = np.arange(30, 71, 2)
print(even_integers)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [7]:
import numpy as np
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
